language: csharp
solution: FileSystemSearcher.sln
script:
  - xbuild /p:Configuration=Release FileSystemSearcher.sln
  - mono ./packages/xunit.runner.console.2.1.0/tools/xunit.console.exe ./EdlinSoftware.GlobFinder.Tests/bin/Release/EdlinSoftware.FileSystemSearcher.Tests.dll